# Generated by Django 3.2 on 2021-05-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mashup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
